name: OpenSSF Scorecard

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload Scorecard results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
